name: Mirror onlyreplace branch to Bitbucket
on:
  push:
    branches:
      - onlyreplace
jobs:
  github-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git remote add dest1 https://x-token-auth:${{ secrets.BB_MIRROR_TOKEN_ONLYREPLACE }}@bitbucket.org/haukex/file-replace.git
      - run: git fetch dest1 onlyreplace
      - run: git push dest1 onlyreplace
