name: Mirror this repo to a remote server
on:
  push:
    branches:
      - fancyreplace
jobs:
  github-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git remote add dest1 https://x-token-auth:${{ secrets.BB_MIRROR_TOKEN_FANCYREPLACE }}@bitbucket.org/haukex/file-replace-fancy.git
      - run: git fetch dest1
      - run: git push dest1
